### ISSUE TITLE
Error when initializing SlalomModel object

### ISSUE THREAD

**Issue by leonfodoulian** [PMBio/slalom#10]
Hi Davis,

I am trying to run `slalom` on a UMI based single-cell RNA-seq dataset, but I keep on getting an error. In fact, there are two types of errors, that I think are unrelated. The `genesets` file I am using for the moment is the one provided with the package.

The first error I am getting is the following, and I can't figure out the source of the error:

```R
> # Locate gmt file
> gmtfile <- system.file("extdata", "reactome_subset.gmt", package = "slalom")
> # Load gmt file
> genesets <- GSEABase::getGmt(gmtfile)
> # Create new SlalomModel object 
> model <- newSlalomModel(object = sce, 
+                         genesets = genesets, 
+                         n_hidden = 5, 
+                         assay_name = "logcounts", 
+                         verbose = TRUE)
24 annotated factors retained;  6 annotated factors dropped.
922  genes retained for analysis.
> # Initialize SlalomModel object
> model <- initSlalom(object = model)
Error in qr.default(Y, complete = FALSE) : 
  NA/NaN/Inf in foreign function call (arg 1)
```

The second error occurs when I change the input to the `assay_name` argument of the `newSlalomModel()` function:

```R
> # Create new SlalomModel object 
> model <- newSlalomModel(object = sce, 
+                         genesets = genesets, 
+                         n_hidden = 5, 
+                         assay_name = "lognorm_scale1e4", 
+                         verbose = TRUE)
24 annotated factors retained;  6 annotated factors dropped.
922  genes retained for analysis.
> # Initialize SlalomModel object
> model <- initSlalom(object = model)
Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
```

I first thought that the function was unable to locate `lognorm_scale1e4` in the `sce`. But this second error is completely unexpected as I get no errors when I run the following (see [line 67 in SlalomModel-methods.R](https://github.com/PMBio/Rslalom/blob/99f2337cde109bede05e38d716c4d0ba6932543c/R/SlalomModel-methods.R#L67)):

```R
> Y <- t(SummarizedExperiment::assay(x = sce, i = "lognorm_scale1e4"))
```
Note also that the `lognorm_scale1e4` matrix is present in my SCE object:

```R
> sce
class: SingleCellExperiment 
dim: 17173 593 
metadata(1): log.exprs.offset
assays(3): counts logcounts lognorm_scale1e4
rownames(17173): 0610007P14Rik 0610009B22Rik ... eGFP l7Rn6
rowData names(9): is_feature_control is_feature_control_MT ... total_counts log10_total_counts
colnames(593): LFHT2_ROW01_01 LFHT2_ROW01_02 ... LFHT2_ROW40_19 LFHT2_ROW40_20
colData names(35): total_features log10_total_features ... neg.sf outlier
reducedDimNames(0):
spikeNames(1): MT
```

Any idea why these errors are occurring? I am going to try to investigate more on this issue, and hopefully quickly find a source or solution. 

Thank you in advance for your help!

Best,
Leon

**Comment by leonfodoulian** [comment]
Hi again,

It seems that both errors occur when `rsvd::rpca()` is called in `.initializePCARand` (see [lines 330 to 343 in SlalomModel-methods.R](https://github.com/PMBio/Rslalom/blob/99f2337cde109bede05e38d716c4d0ba6932543c/R/SlalomModel-methods.R#L330-L343)). I have 593 cells in my dataset, so `rsvd::rpca()` is called instead of `stats::prcomp()`. Note that this latter does not give an error on my data when `lognorm_scale1e4` is used as input to `assay_name` when creating the model. 

Regarding the first error, which occurs when `logcounts` is used as assay, there is another issue. In fact, `logcounts` in `sce` were compute using `scran::computeSumFactors()` while enforcing positive estimates. When running `initSlalom(object = model)`, [lines 234 to 235 in SlalomModel-methods.R](https://github.com/PMBio/Rslalom/blob/99f2337cde109bede05e38d716c4d0ba6932543c/R/SlalomModel-methods.R#L234-L235) give `NA` values, which I think are the source of this error. I however have no idea why this is occurring. 

Best,
Leon

**Comment by leonfodoulian** [comment]
I have to mention also that when I subsample 499 cells from `sce`, I manage to make `slalom` work on my data:

```R
> # Randomly sample 499 cells from sce
> sce <- sce[, sample(x = colnames(x = counts(sce)), size = 499)]
> # Create new SlalomModel object 
> model <- newSlalomModel(object = sce, 
+                         genesets = genesets, 
+                         n_hidden = 5, 
+                         assay_name = "lognorm_scale1e4", 
+                         verbose = TRUE)
24 annotated factors retained;  6 annotated factors dropped.
922  genes retained for analysis.
> # Initialize SlalomModel object
> model <- initSlalom(object = model)
> # Train SlalomModel object
> model <- trainSlalom(object = model, 
+                      nIterations = 1000)
pre-training model for faster convergence
iteration 0
Model not converged after 50 iterations.
iteration 0
Model not converged after 50 iterations.
iteration 0
Switched off factor 24
Switched off factor 11
Switched off factor 7
Switched off factor 28
iteration 100
iteration 200
Switched off factor 27
iteration 300
iteration 400
iteration 500
iteration 600
iteration 700
iteration 800
iteration 900
iteration 1000
Model not converged after 1000 iterations.
```

Therefore, I think that the problem is inherent to `rsvd::rpca()`. I have never used this package to compute PCA, so I don't know what is going wrong here. 

Best,
Leon

**Comment by leonfodoulian** [comment]
I'm sorry I haven't included a `traceback` to the error:

```R
> # Create new SlalomModel object 
> model <- newSlalomModel(object = sce, 
+                         genesets = genesets, 
+                         n_hidden = 5, 
+                         assay_name = "lognorm_scale1e4", 
+                         verbose = TRUE)
24 annotated factors retained;  6 annotated factors dropped.
922  genes retained for analysis.
> # Initialize SlalomModel object
> model <- initSlalom(object = model)
Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
> traceback()
7: array(STATS, dims[perm])
6: aperm(array(STATS, dims[perm]), order(perm))
5: sweep(out$u[, 1:k], MARGIN = 2, STATS = out$d[1:k], FUN = "*", 
       check.margin = TRUE)
4: rpca.default(Ystd[, Ion[, k]], k = 1, retx = TRUE)
3: rsvd::rpca(Ystd[, Ion[, k]], k = 1, retx = TRUE)
2: .initializePCARand(object, seed = seed, save_init = save_init)
1: initSlalom(object = model)
```

You can also find in the following [link](https://stackoverflow.com/questions/23271878/error-in-using-the-predict-function/) other instances where this error occurs, which is related to the `sweep()` function of base R.

**Comment by davismcc** [comment]
Thanks for the bug report. This should be fixed in [a recent commit](https://github.com/PMBio/Rslalom/commit/21f69dd13b09fec75dda3dbafffccd5e64034006).
